### ISSUE TITLE
Change behavior to close after queue is empty

### ISSUE THREAD

**Issue by bwbroersma** [Rich-Harris/yootils#3]
Currently yootils queue is set to close before actually finishing the promise, making it unpractical to add a task, `await queue.close()` and in that task adding more tasks, which will currently fail because `close = true` is set on calling awaiting `close`.

https://github.com/Rich-Harris/yootils/blob/79070c4c811356a9f9dc49355e022d9653a752b8/src/async/queue.ts#L58-L68

**Comment by Rich-Harris** [comment]
Thank you! Sorry for the delayed response. I'm not sure if these are the most desirable semantics though — isn't it confusing if you can add a task after calling `q.close()`? 

I *do* like the idea of `q.close` returning a promise that resolves when all items have completed though.

**Comment by bwbroersma** [comment]
Yeah, I agree, it was mainly a fix to https://github.com/sveltejs/sapper/issues/604 and it's more a `closeWhenEmpty` now.

**Comment by Rich-Harris** [comment]
Found an alternative solution in https://github.com/sveltejs/sapper/pull/605, so we can keep the existing semantics of `q.close` — I'll close this. I've merged the additional tests from #4 though — thank you!
